run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - internal/testdata

linters-settings:
  goimports:
    local-prefixes: beacon
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  misspell:
    locale: US
  prealloc:
    simple: true
    for-loops: true
  unparam:
    check-exported: false
  whitespace:
    multi-indent: false

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - revive
    - gocyclo
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - lll
    - nakedret
    - prealloc
    - rowserrcheck
    - sqlnorows
    - stylecheck
    - unconvert
    - unparam
    - whitespace
    - wsl

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0